[doc]
name = 'mangkoran-vita'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'mangkoran-resume'
type = 'pdf'
index = 'mangkoran-resume.tex'
preamble = ''
postamble = ''
